# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='observer',
            field=models.CharField(max_length=20),
        ),
    ]
